-- Desactivar RLS temporalmente para debugging
ALTER TABLE businesses DISABLE ROW LEVEL SECURITY;
ALTER TABLE clients DISABLE ROW LEVEL SECURITY;
ALTER TABLE promotions DISABLE ROW LEVEL SECURITY;
ALTER TABLE menus_dia DISABLE ROW LEVEL SECURITY; 